spring:
  datasource:
    url: jdbc:postgresql://coldchain-db.cj424egoet74.eu-north-1.rds.amazonaws.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: eu-north-1
      s3:
        bucket: cold-chain-audit-ankush
      
  jpa:
    hibernate:
      ddl-auto: update # This automatically creates the table for you
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


